id: P009638
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:42:14.767684
source_metadata:
  id: bdr:W1KG6162
  title: སི་ཁྲོན་བོད་རིག་པའི་ཞིབ་འཇུག ༼༡༠༽
  author: ''
  volumes:
    963a149802d24e3d8657932a8a19cf20:
      image_group_id: I1KG8427
      title: ''
      volume_number: 1
      total_pages: 576
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
