id: IAB000A1A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:05:15+00:00'
last_modified: '2022-06-08T12:27:31.013669+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6162
  title: སི་ཁྲོན་བོད་རིག་པའི་ཞིབ་འཇུག ༼༡༠༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    BA8B:
      image_group_id: I1KG8427
      title: ''
      total_pages: 576
      order: 1
      base_file: BA8B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
